//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosplayWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string Comment1 { get; set; }
        public int Likes { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Gallery_ID { get; set; }
        public string Cust_ID { get; set; }
        public string Seller_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Gallery Gallery { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
