//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosplayWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gallery()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public string Gallery_ID { get; set; }
        public string Gallery_Img { get; set; }
        public string Gallery_Desc { get; set; }
        public Nullable<System.DateTime> Gallery_Date { get; set; }
        public string Gallery_Tag { get; set; }
        public string Cust_ID { get; set; }
        public string Seller_ID { get; set; }
        public int Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
