//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosplayWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_detail
    {
        public string Pay_ID { get; set; }
        public string Prod_ID { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Product Product { get; set; }
    }
}
