//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosplayWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Cartlists = new HashSet<Cartlist>();
            this.Payment_detail = new HashSet<Payment_detail>();
            this.Wishlists = new HashSet<Wishlist>();
        }
    
        public string Prod_ID { get; set; }
        public string Prod_Name { get; set; }
        public Nullable<decimal> Prod_Price { get; set; }
        public string Prod_Details { get; set; }
        public Nullable<int> Prod_Count { get; set; }
        public Nullable<double> Prod_Rate { get; set; }
        public string Prod_Image { get; set; }
        public string Prod_Status { get; set; }
        public string Rate_ID { get; set; }
        public string Cat_ID { get; set; }
        public string Seller_ID { get; set; }
        public string Sort_ID { get; set; }
        public string Prod_Tag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cartlist> Cartlists { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_detail> Payment_detail { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual Sort Sort { get; set; }
        public virtual Rating Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wishlist> Wishlists { get; set; }
    }
}
