//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosplayWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string Trans_ID { get; set; }
        public string pay_ID { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
